default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: orderManagerdb_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: orderManagerdb_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  primary:
    <<: *default
    database: storage/production.sqlite3
